"""Ponta a ponta offline: `--ig-session` -> jar -> header Cookie -> pastas.

Roda o caminho REAL do CLI (`run_profile_mode`) contra um Instagram falso, para
provar as tres coisas que um teste de unidade nao prova de uma vez:

1. o valor colado chega gravado no `cookies.txt`, com o prefixo `#HttpOnly_`;
2. a requisicao GraphQL sai com `sessionid=<valor>` no header `Cookie`;
3. os itens caem em `reels/` e `posts/` conforme o `product_type`.

O download da midia (yt-dlp) e substituido: nao ha rede aqui.

Uso: python ig_session_check.py
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from viralclipper import cli, config as config_mod, download, ig_profile  # noqa: E402
from viralclipper.util import Logger  # noqa: E402

PAGE_HTML = (
    "<html><head>"
    '<meta property="og:title" content="Conta de Teste (@conta) • Instagram photos and videos">'
    "</head><body>"
    '<script>window.__b = {"LSD",[],{"token":"LSDTOKEN123"}};</script>'
    "</body></html>"
)

PAGE_JSON = {
    "data": {
        ig_profile.ROOT_FIELD: {
            "edges": [
                {
                    "node": {
                        "id": "111",
                        "code": "REEL001",
                        "media_type": 2,
                        "product_type": "clips",
                        "video_duration": 12.5,
                        "caption": {"text": "primeiro reel"},
                    }
                },
                {
                    "node": {
                        "id": "222",
                        "code": "POST002",
                        "media_type": 2,
                        "product_type": "feed",
                        "video_duration": 30.0,
                        "caption": {"text": "primeiro post"},
                    }
                },
                {
                    "node": {
                        "id": "333",
                        "code": "FOTO003",
                        "media_type": 1,
                        "product_type": "feed",
                        "caption": {"text": "foto, deve ser pulada"},
                    }
                },
            ],
            "page_info": {"has_next_page": False, "end_cursor": None},
        }
    }
}


class FakeResponse:
    def __init__(self, body: bytes):
        self._body = body

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False

    def read(self) -> bytes:
        return self._body


def main() -> int:
    seen = {"get": None, "post": None}

    def fake_urlopen(request, timeout=None):
        cookie = request.get_header("Cookie") or ""
        if request.get_method() == "POST":
            seen["post"] = cookie
            return FakeResponse(json.dumps(PAGE_JSON).encode())
        seen["get"] = cookie
        return FakeResponse(PAGE_HTML.encode())

    workdir = Path(tempfile.mkdtemp(prefix="vc_e2e_"))
    jar = workdir / "cookies.txt"
    jar.write_text(
        "# Netscape HTTP Cookie File\n"
        "# This file is generated by yt-dlp.  Do not edit.\n"
        ".instagram.com\tTRUE\t/\tTRUE\t1824776458\tcsrftoken\tCSRFABC\n"
        ".instagram.com\tTRUE\t/\tTRUE\t1797992458\tds_user_id\t4242\n",
        encoding="utf-8",
    )
    before = jar.read_text(encoding="utf-8")

    config = config_mod.ClipConfig(url="", output_dir=str(workdir / "out"))
    config.quiet = True
    logger = Logger(quiet=False, verbose=False)

    def fake_download(url, destination, cfg, log=None, **kwargs):
        path = Path(destination)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"fake")
        return path

    checks: list[tuple[str, bool, str]] = []
    with mock.patch("urllib.request.urlopen", side_effect=fake_urlopen), mock.patch.object(
        download, "download_media", side_effect=fake_download
    ):
        code = cli.run_profile_mode(
            config, "@conta", str(jar), logger, session="1234:abcXYZ", max_items=5
        )

    after = jar.read_text(encoding="utf-8")
    added = [ln for ln in after.splitlines() if ln not in before.splitlines()]

    checks.append(("run_profile_mode devolveu 0", code == 0, f"code={code}"))
    checks.append(
        (
            "linha gravada com prefixo #HttpOnly_ e valor normalizado",
            len(added) == 1 and added[0].startswith("#HttpOnly_.instagram.com\t")
            and added[0].split("\t")[5] == "sessionid"
            and added[0].split("\t")[6] == "1234%3AabcXYZ",
            f"added={added}",
        )
    )
    checks.append(
        (
            "as linhas antigas ficaram intactas",
            all(ln in after for ln in before.splitlines()),
            "",
        )
    )
    checks.append(
        (
            "GET do perfil levou o sessionid",
            seen["get"] is not None and "sessionid=1234%3AabcXYZ" in seen["get"],
            f"cookie={seen['get']}",
        )
    )
    checks.append(
        (
            "POST graphql levou o sessionid e o csrftoken",
            seen["post"] is not None
            and "sessionid=1234%3AabcXYZ" in seen["post"]
            and "csrftoken=CSRFABC" in seen["post"],
            f"cookie={seen['post']}",
        )
    )
    reels = sorted(p.name for p in (Path(config.output_dir) / "reels").glob("*"))
    posts = sorted(p.name for p in (Path(config.output_dir) / "posts").glob("*"))
    checks.append(("reel em reels/", len(reels) == 1, f"reels={reels}"))
    checks.append(("post em posts/", len(posts) == 1, f"posts={posts}"))
    checks.append(("foto pulada", "FOTO003" not in "".join(reels + posts), f"{reels + posts}"))

    # Segunda passada: sem colar nada, o que esta no arquivo tem de bastar.
    seen["post"] = None
    with mock.patch("urllib.request.urlopen", side_effect=fake_urlopen), mock.patch.object(
        download, "download_media", side_effect=fake_download
    ):
        code2 = cli.run_profile_mode(config, "@conta", str(jar), logger, max_items=5)
    checks.append(("2a passada sem colar: devolve 0", code2 == 0, f"code={code2}"))
    checks.append(
        (
            "2a passada sem colar: a sessao do arquivo viajou",
            seen["post"] is not None and "sessionid=1234%3AabcXYZ" in seen["post"],
            f"cookie={seen['post']}",
        )
    )
    checks.append(("2a passada nao duplicou a linha", jar.read_text(encoding="utf-8").count("sessionid") == 1, ""))

    ok = True
    for label, passed, detail in checks:
        ok = ok and passed
        print(f"[{'ok ' if passed else 'FALHA'}] {label}" + (f"   {detail}" if detail and not passed else ""))
    print(f"\nworkdir: {workdir}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
